language: cpp
os: linux
services:
  - docker
compiler:
  - gcc
  - clang
env:
  - IMAGE=ubuntu:latest
  - IMAGE=ubuntu:rolling
  - IMAGE=ubuntu:devel
before_install:
  - docker build --build-arg IMAGE=$IMAGE -t $IMAGE -f test/dockerfiles/Dockerfile.$IMAGE .
script:
  - docker run -e CC -e CXX $IMAGE
