language: cpp
os: linux
dist: bionic
services:
  - docker
env:
  - IMAGE=ubuntu:latest DOCKERFILE=debian
  - IMAGE=ubuntu:rolling DOCKERFILE=debian
  - IMAGE=ubuntu:devel DOCKERFILE=debian
  - IMAGE=debian:stable DOCKERFILE=debian
  - IMAGE=debian:testing DOCKERFILE=debian
  - IMAGE=debian:unstable DOCKERFILE=debian
  - IMAGE=opensuse/leap:latest DOCKERFILE=opensuse
  - IMAGE=opensuse/tumbleweed:latest DOCKERFILE=opensuse
jobs:
  allow_failures:
    - env: IMAGE=debian:stable DOCKERFILE=debian
    - env: IMAGE=debian:testing DOCKERFILE=debian
    - env: IMAGE=debian:unstable DOCKERFILE=debian
    - env: IMAGE=opensuse/leap:latest DOCKERFILE=opensuse
    - env: IMAGE=opensuse/tumbleweed:latest DOCKERFILE=opensuse
before_install:
  - docker build --build-arg IMAGE=$IMAGE -t img -f test/dockerfiles/Dockerfile.$DOCKERFILE .
script:
  - docker run img
